<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="integration.Customer"
					targetNamespace="urn:org.redhat.integration.cd.customer" 
					xmlns:tns="urn:org.redhat.integration.cd.customer" 
					xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
					xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:documentation>Version 1.2</wsdl:documentation>


  <wsdl:types>
    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema" 
    			xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="urn:org.redhat.integration.cd.customer" schemaLocation="getCustomer_types.xsd"/>
      <xsd:import namespace="urn:org.redhat.integration.cd.customer" schemaLocation="getCustomer_fault.xsd"/>
    </xsd:schema>
  </wsdl:types>



  <wsdl:message name="getCustomerRequestMessage">
    <wsdl:part element="tns:getCustomerRequest" name="payload"/>
  </wsdl:message>

  <wsdl:message name="getCustomerResponseMessage">
    <wsdl:part element="tns:getCustomerResponse" name="payload"/>
  </wsdl:message>


  <wsdl:message name="getCustomerFaultMessage">
    <wsdl:part element="tns:getCustomerFault" name="payload"/>
  </wsdl:message>


 
  <wsdl:portType name="integration.port.Customer">
    <wsdl:operation name="getCustomer">
      <wsdl:input message="tns:getCustomerRequestMessage"/>
      <wsdl:output message="tns:getCustomerResponseMessage"/>
      <wsdl:fault message="tns:getCustomerFaultMessage" name="fault"/>
    </wsdl:operation>
  </wsdl:portType>


 
  <wsdl:binding name="integration.binding.Customer.Binding" type="tns:integration.port.Customer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getCustomer">
      <soap:operation soapAction="getCustomer" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="fault">
        <soap:fault name="fault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>


  <wsdl:service name="integration.svc.Customer.BindingQSService">
    <wsdl:port binding="tns:integration.binding.Customer.Binding" name="integration.binding.Customer.BindingQSPort">
      <soap:address location="http://localhost:8090/getCustomer"/>
    </wsdl:port>
  </wsdl:service>

  
</wsdl:definitions>
